#!/usr/bin/env python
import matplotlib.pyplot as plt
import xarray as xr
import numpy as np


def calc_diff(arr1, arr2):
  diff = arr1 - np.flip(arr2, axis=1)
  return diff


def comp_1(var, tstep=0):
  '''
  Trying to compare Helene's downscaled file to the one generated by the 
  refactored process (this codebase).

  So far tair and vapor_press look decent, but nirr and precip are off by quite
  a bit.
  '''
  VAR = var
  TSTEP = tstep


  rt = xr.open_dataset("working/05-tiles-TEM/H00_V08/historic-climate.nc")
  hg = xr.open_dataset("hg-samples/H01_V09/input/historic-climate.nc")

  diff = calc_diff(rt[VAR].data, hg[VAR].data)
  diff_min = np.abs(np.nanmin(diff.flatten()))
  diff_max = np.abs(np.nanmax(diff.flatten()))

  limit = max(diff_min, diff_max)
  print(f"max abs diff = {limit}")


  fig, axes = plt.subplots(1,3, figsize=(12,6))

  rt_max = np.nanmax(rt[VAR][TSTEP].data)
  rt_min = np.nanmin(rt[VAR][TSTEP].data)
  hg_max = np.nanmax(hg[VAR][TSTEP].data)
  hg_min = np.nanmin(hg[VAR][TSTEP].data)

  print(f"rt {VAR} min={rt_min}, max={rt_max}")
  print(f"hg {VAR} min={hg_min}, max={hg_max}")   

  cbar_min = min(rt_min, hg_min)
  cbar_max = max(rt_max, hg_max)
  print(f"cbar min={cbar_min}, max={cbar_max}")

  # This s
  # 
  # ection indicates that we need to flip the Helene data vertically.
  # rtim = axes[0,0].imshow(rt[VAR][TSTEP].data, origin='lower')
  # hgim = axes[0,1].imshow(hg[VAR][TSTEP].data, origin='lower')
  # diff = axes[0,2].imshow( (rt[VAR][TSTEP].data - hg[VAR][TSTEP].data), origin='lower')
  # plt.colorbar(rtim, ax=axes[0,0])
  # plt.colorbar(hgim, ax=axes[0,1])
  # plt.colorbar(diff, ax=axes[0,2])

  # This is the flipped comparison...
  flipped_hg = np.flip(hg[VAR][TSTEP].data, axis=0)
  rtim = axes[0].imshow(rt[VAR][TSTEP].data, origin='lower', vmin=cbar_min, vmax=cbar_max)
  hgim = axes[1].imshow(flipped_hg, origin='lower', vmin=cbar_min, vmax=cbar_max)
  diff = axes[2].imshow( diff[TSTEP], origin='lower', cmap='coolwarm', vmin=-limit, vmax=limit)
  #diff = axes[0,2].imshow( (rt[VAR][TSTEP].data - flipped_hg), origin='lower')


  axes[0].set_title('Refactored TEMDS')
  axes[1].set_title("Helene's downscaling")
  axes[2].set_title('Difference (ref - helene)')

  plt.colorbar(rtim, ax=axes[0])
  plt.colorbar(hgim, ax=axes[1])
  plt.colorbar(diff, ax=axes[2])

  plt.suptitle(f'Comparison of {VAR} at time step {TSTEP}')
  plt.tight_layout

  plt.show()

def comp2(var):
  rt = xr.open_dataset("working/05-tiles-TEM/H00_V08/historic-climate.nc")
  hg = xr.open_dataset("hg-samples/H01_V09/input/historic-climate.nc")

  VAR = var

  fig, axes = plt.subplots(2,1, figsize=(12,6))

  diff = calc_diff(rt[VAR].data, hg[VAR].data)

  diffbox = axes[0].boxplot(diff.flatten(), whis=[5, 95], showfliers=True)

  ts_diff_min = np.nanmin(diff, axis=(1,2))
  ts_diff_max = np.nanmax(diff, axis=(1,2))

  diffts_min = axes[1].plot(ts_diff_min, label='min')
  diffts_max = axes[1].plot(ts_diff_max, label='max')