#!/usr/bin/env python
import matplotlib.pyplot as plt
import xarray as xr
import numpy as np


def comp_1(var, tstep=0):
  '''
  Trying to compare Helene's downscaled file to the one generated by the 
  refactored process (this codebase).

  So far tair and vapor_press look decent, but nirr and precip are off by quite
  a bit.
  '''
  rt = xr.open_dataset("working/05-tiles-TEM/H00_V08/historic-climate.nc")
  hg = xr.open_dataset("hg-samples/H01_V09/input/historic-climate.nc")

  VAR = var
  TSTEP = tstep

  fig, axes = plt.subplots(1,3, figsize=(12,6))

  # This section indicates that we need to flip the Helene data vertically.
  # rtim = axes[0,0].imshow(rt[VAR][TSTEP].data, origin='lower')
  # hgim = axes[0,1].imshow(hg[VAR][TSTEP].data, origin='lower')
  # diff = axes[0,2].imshow( (rt[VAR][TSTEP].data - hg[VAR][TSTEP].data), origin='lower')
  # plt.colorbar(rtim, ax=axes[0,0])
  # plt.colorbar(hgim, ax=axes[0,1])
  # plt.colorbar(diff, ax=axes[0,2])

  # This is the flipped comparison...
  flipped_hg = np.flip(hg[VAR][TSTEP].data, axis=0)
  rtim = axes[0].imshow(rt[VAR][TSTEP].data, origin='lower')
  hgim = axes[1].imshow(flipped_hg, origin='lower')
  diff = axes[2].imshow( (rt[VAR][TSTEP].data - hg[VAR][TSTEP].data[::-1]), origin='lower')
  #diff = axes[0,2].imshow( (rt[VAR][TSTEP].data - flipped_hg), origin='lower')

  axes[0].set_title('Refactored TEMDS')
  axes[1].set_title("Helene's downscaling")
  axes[2].set_title('Difference (ref - helene)')

  plt.colorbar(rtim, ax=axes[0])
  plt.colorbar(hgim, ax=axes[1])
  plt.colorbar(diff, ax=axes[2])

  plt.tight_layout

  plt.show()